import React from 'react';
import {
    Lightbulb,
    CheckCircle2,
    XCircle,
    MessageCircleQuestion ,
    Zap,
    TrendingUp,
    AlertTriangle,
    Clock
} from 'lucide-react';
import toast from 'react-hot-toast';

// --- HIGH FIDELITY DUMMY DATA ---
const SUGGESTIONS = [
    {
        id: 1,
        priority: 'Urgent',
        title: 'Reassign Task: Backend API (PROJ-22)',
        reason: 'John Doe is currently at 115% workload capacity. This task is a blocker for 3 other frontend tasks.',
        impact: 'Reduces John\'s load (115% → 75%) and saves ~2 days of project delay.',
        type: 'reassignment'
    },
    {
        id: 2,
        priority: 'Soon',
        title: 'Add 2-Day Buffer to Sprint 4',
        reason: 'AI detected that current velocity is 10% lower than historical average for "Complex UI" tasks.',
        impact: 'Increases Sprint success probability from 64% → 89%.',
        type: 'deadline'
    },
    {
        id: 3,
        priority: 'Optional',
        title: 'Schedule Skill-Sync Meeting',
        reason: 'Multiple conflicting comments detected on PROJ-40 specs between UI and Backend teams.',
        impact: 'Prevents potential "re-work" and clarifies 12 unresolved requirements.',
        type: 'meeting'
    },
    {
        id: 4,
        priority: 'Urgent',
        title: 'Swap Assignee: QA Testing',
        reason: 'The current tester (Emma) has no experience in "Security Testing" required for PROJ-50.',
        impact: 'Reduces bug re-open rate by predicted 30% for the upcoming release.',
        type: 'reassignment'
    },
];

const SuggestionsBoard = () => {

    const handleAskWhy = (title) => {
        toast(`Opening Co-Pilot to explain reasoning for: ${title}`, {
            icon: '🤖',
            style: { borderRadius: '10px', background: '#2c3e50', color: '#fff' }
        });
        // Logic to trigger the sidebar chat drawer would go here
    };

    const getPriorityStyle = (priority) => {
        if (priority === 'Urgent') return 'bg-red-50 text-red-600 border-red-100';
        if (priority === 'Soon') return 'bg-yellow-50 text-yellow-600 border-yellow-100';
        return 'bg-blue-50 text-blue-600 border-blue-100';
    };

    return (
        <div className="space-y-6 lg:space-y-8 animate-in fade-in duration-500 pb-12">

            {/* 1. HEADER */}
            <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-[#2c3e50]">AI Suggestions Board</h1>
                    <p className="text-sm text-gray-500 mt-1">Intelligent recommendations generated by the Agentic AI Decision Engine.</p>
                </div>
                <div className="flex items-center gap-2 bg-white px-4 py-2 rounded-xl shadow-sm border border-gray-100">
                    <Zap size={16} className="text-[#18bc9c]" />
                    <span className="text-xs font-bold text-[#2c3e50]">4 Active Suggestions</span>
                </div>
            </header>

            {/* 2. SUGGESTIONS LIST */}
            <div className="grid grid-cols-1 gap-6">
                {SUGGESTIONS.map((item) => (
                    <div key={item.id} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 flex flex-col lg:flex-row gap-6 hover:shadow-md transition-all group">

                        {/* Left: Icon & Priority */}
                        <div className="flex flex-col items-center shrink-0">
                            <div className="w-14 h-14 bg-[#18bc9c]/10 rounded-2xl flex items-center justify-center text-[#18bc9c] mb-3 group-hover:scale-110 transition-transform">
                                <Lightbulb size={28} />
                            </div>
                            <span className={`text-[9px] font-black uppercase px-2.5 py-1 rounded-full border ${getPriorityStyle(item.priority)}`}>
                                {item.priority}
                            </span>
                        </div>

                        {/* Middle: Content */}
                        <div className="flex-1 space-y-4">
                            <div>
                                <h3 className="text-lg font-bold text-[#2c3e50] group-hover:text-[#18bc9c] transition-colors">
                                    {item.title}
                                </h3>
                                <div className="bg-gray-50 p-4 rounded-xl mt-3 border-l-4 border-gray-200 text-xs lg:text-sm text-gray-600 leading-relaxed italic">
                                    "AI Reasoning: {item.reason}"
                                </div>
                            </div>

                            {/* IMPACT PREVIEW BOX (NEW FEATURE) */}
                            <div className="bg-[#18bc9c]/5 border border-[#18bc9c]/20 p-4 rounded-xl flex items-center gap-4">
                                <div className="p-2 bg-[#18bc9c] text-white rounded-lg">
                                    <TrendingUp size={16} />
                                </div>
                                <div>
                                    <h4 className="text-[10px] font-black text-[#18bc9c] uppercase tracking-widest">Impact Preview</h4>
                                    <p className="text-xs font-bold text-[#2c3e50]">{item.impact}</p>
                                </div>
                            </div>

                            {/* Bottom Actions */}
                            <div className="flex flex-wrap items-center justify-between gap-4 pt-2">
                                <div className="flex gap-2">
                                    <button className="flex items-center gap-2 bg-[#18bc9c] text-white px-5 py-2.5 rounded-xl font-bold text-xs hover:bg-[#128f76] transition-all shadow-lg shadow-[#18bc9c]/20">
                                        <CheckCircle2 size={16} /> Approve & Sync Jira
                                    </button>
                                    <button className="flex items-center gap-2 border border-gray-200 text-gray-500 px-5 py-2.5 rounded-xl font-bold text-xs hover:bg-gray-50 transition-all">
                                        <XCircle size={16} /> Ignore
                                    </button>
                                </div>

                                {/* ASK WHY BUTTON (NEW FEATURE) */}
                                <button
                                    onClick={() => handleAskWhy(item.title)}
                                    className="flex items-center gap-2 text-[#2c3e50] hover:text-[#18bc9c] font-bold text-xs transition-colors px-4 py-2 rounded-lg hover:bg-gray-50"
                                >
                                    <MessageCircleQuestion  size={16} /> Ask AI Why?
                                </button>
                            </div>
                        </div>

                    </div>
                ))}
            </div>

            {/* FOOTER INFO */}
            <div className="flex items-center gap-2 justify-center py-6">
                <AlertTriangle size={14} className="text-gray-400" />
                <p className="text-[10px] text-gray-400 font-medium">All approved suggestions will automatically update your connected Jira Cloud workspace.</p>
            </div>

        </div>
    );
};

export default SuggestionsBoard;